### ISSUE TITLE
Build Step : Assets

### ISSUE THREAD

**Issue by brockdusome** [stolksdorf/vitreum-cli#2]
Identified incorrect variables are being plugged into `assets` step in **build** and **dev** scripts. The variables already exist in the project setup, the keys being passed just need to change.

**Current:**
```js
.then(() => steps.assetsWatch(Proj.assets, Proj.shared))
```
Based on the structure of `project.js` the correct variables from `Proj` should be:
```js
.then(() => steps.assetsWatch(Proj.assetExts, Proj.assets))
```

After making these changes in my project, Vitreum is now successfully pulling assets in on build!

💡  **Suggestion** — Also wouldn't be a bad idea to consider renaming `assets` to `assetsPath` by default just for additional clarity.

**Comment by stolksdorf** [comment]
Fixed in v1.4.1
